trigger:
- main

pool:
  name: AgentDummy

variables:
  buildConfiguration: 'Release'
  imageRepository: 'gozul/dotnet-album-viewer'
  dockerRegistryServiceConnection: 'DockerHub'
  sonarProjectKey: 'dummy-project-key'
  sonarProjectName: 'dummy-project'
  sonarHostUrl: 'http://localhost:9000'
  imageTag: '$(Build.BuildId)'
  k8sNamespace: 'dummy-app'

stages:
- stage: AnalyzeBuild
  displayName: 'Analyze and Build'
  jobs:
  - job: SonarBuild
    displayName: 'SonarQube + Build .NET'
    steps:
    - checkout: self
      fetchDepth: 0

    - task: UseDotNet@2
      displayName: 'Instalar .NET SDK 8'
      inputs:
        packageType: 'sdk'
        version: '8.0.x'

    - powershell: |
        dotnet tool install --global dotnet-sonarscanner --version 6.*
        $env:PATH += ";$env:USERPROFILE\.dotnet\tools"

        dotnet sonarscanner begin `
          /k:"$(sonarProjectKey)" `
          /n:"$(sonarProjectName)" `
          /d:sonar.host.url="$(sonarHostUrl)" `
          /d:sonar.token="$(SONAR_TOKEN)" `
          /d:sonar.verbose=true

        dotnet restore .\src\AlbumViewerNetCore\AlbumViewerNetCore.csproj
        dotnet build .\src\AlbumViewerNetCore\AlbumViewerNetCore.csproj --configuration $(buildConfiguration) --no-restore

        dotnet sonarscanner end /d:sonar.token="$(SONAR_TOKEN)"
      displayName: 'SonarScanner for .NET manual'
      env:
        SONAR_TOKEN: $(SONAR_TOKEN)

- stage: Dockerize
  displayName: 'Build and Push Image'
  dependsOn: AnalyzeBuild
  condition: succeeded()
  jobs:
  - job: DockerBuildPush
    displayName: 'Docker Build and Push'
    steps:
    - task: Docker@2
      displayName: 'Build and Push Docker image'
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: 'docker/app/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: |
          $(imageTag)
          latest

- stage: Deploy
  displayName: 'Deploy to Minikube'
  dependsOn: Dockerize
  condition: succeeded()
  jobs:
  - job: K8sDeploy
    displayName: 'Apply Kubernetes manifests'
    steps:
    - powershell: |
        kubectl config current-context
        kubectl apply -f environment/namespace.yaml
        kubectl apply -f environment/deployment.yaml
        kubectl apply -f environment/service.yaml
        kubectl apply -f environment/ingress.yaml
        kubectl rollout status deployment/dotnet-album-viewer -n $(k8sNamespace) --timeout=180s
        kubectl get all -n $(k8sNamespace)
        kubectl get ingress -n $(k8sNamespace)
      displayName: 'Deploy manifests'